system:
  plugins_dir: ["plugins"]
  log_level: "INFO"

plugins:
  mumble:
    enabled: true
    log_level: "INFO"
    server:
      host: "localhost"
      port: 64738
  vad:
    enabled: true
    log_level: "INFO"
  transcriber:
    enabled: true
    log_level: "INFO"
    whisperx:
      url: http://localhost:8000
      model: tiny
      diarize: true
      align: true
  system:
    enabled: true
    log_level: "INFO"
  ollama:
    enabled: true
    log_level: "INFO"
    model: "llama3.2:3b"
    temperature: 0.0
    url: "http://localhost:11434"
  shadow:
    enabled: true
    log_level: "INFO"
    model: "llama3.2:3b"
    temperature: 0.0
    url: "http://localhost:11434"
  recorder:
    enabled: false
    log_level: "INFO"
    location: ./.recordings
  telegram_sink:
    enabled: true
    log_level: "INFO"
    telegram_api_id: "<api_id>"
    telegram_api_hash: "<api_hash>"
    telegram_phone_number: "<phone_number>"
    telegram_chat_name: "me"
    telegram_session_name: "anon"
    monitor_telegram_chat: false

